create database playstore;
use playstore
CREATE TABLE IF NOT EXISTS `app_data` (
    IndexNo int unsigned, 
    App VARCHAR(225) NULL,
    Category VARCHAR(225) NULL,
    Rating FLOAT NULL,
    Reviews FLOAT NULL,
    Size VARCHAR(225) NULL,
    Installs FLOAT NULL,
    `Type` VARCHAR(225) NULL,
    Price FLOAT NULL,
    Content_Rating VARCHAR(225) NULL,
    Genres VARCHAR(225) NULL,
    Last_Updated TEXT NULL,
    Current_Ver VARCHAR(225) NULL,
    Android_Ver VARCHAR(225) NULL
);

SET SESSION sql_mode = ''

LOAD DATA INFILE 
'E:/cleaned_app.csv'
INTO TABLE app_data
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

CREATE TABLE IF NOT EXISTS `app_reviews` (
	`IndexNo` INT NOT NULL,
	 App VARCHAR(555) NOT NULL,
     Translated_Review VARCHAR(3500) NOT NULL,
	 Sentiment VARCHAR(50) NOT NULL,
     Sentiment_Polarity FLOAT(10),
     Sentiment_Subjectivity FLOAT(10)
);

LOAD DATA INFILE 'E:/cleaned_reviews_.csv' 
INTO TABLE app_reviews
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

DESC app_data;
SELECT COUNT(*) FROM app_data;

DESC app_reviews;
SELECT COUNT(*) FROM app_reviews;


/* 
1) Which apps have the highest rating in the given available dataset? */
SELECT App, Rating 
FROM app_data 
WHERE Rating = (SELECT MAX(Rating) FROM app_data);

/*
2) What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top. */
SELECT App, Reviews, Installs 
FROM app_data
WHERE Rating= (SELECT MAX(Rating) 
FROM app_data)
ORDER BY Reviews DESC;


---------------------------------------------------------------------------------------------------------------------------------------------------------

/*
3) Which app has the highest number of reviews? Also, mention the number of reviews and category of the app. */
SELECT App, Category, Reviews 
FROM app_data
ORDER BY Reviews DESC 
LIMIT 1;


---------------------------------------------------------------------------------------------------------------------------------------------------------

/* 
4) What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps from the google play store, 
the amount is considered in the revenue) */
SELECT SUM(Price * Installs) AS Total_Revenue 
FROM app_data
WHERE Type = 'Paid';


---------------------------------------------------------------------------------------------------------------------------------------------------------

/* 
5) Which Category of google play store apps has the highest number of installs? Also, find out the total number of installs for that particular category. */
SELECT Category, SUM(Installs) AS Total_Installs 
FROM app_data
ORDER BY Installs DESC LIMIT 1;


---------------------------------------------------------------------------------------------------------------------------------------------------------

/*
6) Which Genre has the most number of published apps? */
SELECT Genres, COUNT(App) AS App_numbers 
FROM app_data
GROUP BY Genres
ORDER BY App_numbers DESC LIMIT 1;


---------------------------------------------------------------------------------------------------------------------------------------------------------

/* 
7) Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top 
  (to avoid duplicate results use distinct) */
SELECT DISTINCT App, Category, Installs 
FROM app_data
WHERE Category = 'GAME'
ORDER BY Installs DESC;


---------------------------------------------------------------------------------------------------------------------------------------------------------

/* 
8) Provide the list of apps that can work on android version '4.0.3 and UP'. */
SELECT DISTINCT App, Android_Ver 
FROM app_data
#WHERE Android_Ver LIKE '%4.0.3 and UP%';
WHERE Android_Ver = '4.0.3 and UP';


---------------------------------------------------------------------------------------------------------------------------------------------------------

/* 
9) How many apps from the given data set are free? Also, provide the number of paid apps. */
SELECT `Type`, COUNT(app) as total_apps_as_per_Type 
FROM app_data
GROUP BY `Type`;


---------------------------------------------------------------------------------------------------------------------------------------------------------

/* 
10)  Which is the best dating app? (Best dating app is the one having the highest number of Reviews) */
SELECT App FROM app_data
WHERE Category LIKE 'DATING'
ORDER BY Reviews DESC LIMIT 1;


---------------------------------------------------------------------------------------------------------------------------------------------------------

/* 
11) Get the number of reviews having positive sentiment and number of reviews having negative sentiment for the app 10 best foods for you 
    and compare them.*/
SELECT App, COUNT(Translated_Review) AS No_of_Reviews, Sentiment 
FROM app_reviews
WHERE App LIKE '10 best foods for you'
GROUP BY Sentiment;

  
---------------------------------------------------------------------------------------------------------------------------------------------------------

/* 
12) Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1? */
SELECT App, Translated_Review AS `Comment`, Sentiment_Polarity, Sentiment_Subjectivity 
FROM app_reviews
WHERE App = 'ASUS SuperNote' AND Sentiment_Polarity = 1 AND Sentiment_Subjectivity = 1;


---------------------------------------------------------------------------------------------------------------------------------------------------------

/*
13) Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat. */
SELECT App, Translated_Review AS `Review`, Sentiment  
FROM app_reviews
WHERE App LIKE 'Abs Training-Burn belly fat' AND Sentiment LIKE 'Neutral';


---------------------------------------------------------------------------------------------------------------------------------------------------------

/* 
14) Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity. */
SELECT App, Translated_Review AS `Review`, Sentiment_Polarity, Sentiment_Subjectivity 
FROM app_reviews
WHERE App = 'Adobe Acrobat Reader' AND Sentiment = 'Negative';





